# Generated by Django 2.1.5 on 2021-06-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='details',
        ),
        migrations.AddField(
            model_name='product',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
